[package]
name = "selector"
version = "0.1.1"
edition.workspace = true
authors.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[lints.rust]
unsafe_code = "allow"

[dependencies]
ndarray = { version = "0.17.2", features = ["rayon"] }
ndarray-rand = "0.16.0"
rayon = "1.11.0"
ndarray-stats = "0.7.0"
thiserror = "2.0.18"
pyo3 = { version = "0.28.3", features = ["extension-module"], optional = true }
numpy = { version = "0.28.0", optional = true }

[features]
default = []
python = ["dep:numpy", "dep:pyo3"]
