[package]
name = "selector"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[lints.rust]
unsafe_code = "allow"

[dependencies]
ndarray = "0.17.2"
ndarray-rand = "0.16.0"
polars = { version = "0.53.0", features = ["lazy"] }

ndarray-linalg = { version = "0.18.1", default-features = false }
rayon = "1.11.0"
ndarray-stats = "0.7.0"

[features]
default = []

openblas = ["ndarray-linalg/openblas-static"]
intel-mkl = ["ndarray-linalg/intel-mkl-static"]
